ext-clickhouse:
  type: php-extension
  artifact:
    source:
      type: git
      url: 'https://github.com/true-async/php-clickhouse.git'
      rev: main
      extract: php-src/ext/clickhouse
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  suggests@unix:
    - openssl
  lang: cpp
  php-extension:
    os:
      - Linux
      - Darwin
    arg-type@unix: custom
